# Generated by Django 3.2.16 on 2023-08-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='inviter_code',
            field=models.CharField(blank=True, max_length=6, verbose_name='Инвайт-код пригласившего'),
        ),
        migrations.AddField(
            model_name='user',
            name='my_invite_code',
            field=models.CharField(blank=True, default='-L5Ziw', max_length=6, verbose_name='Мой инвайт-код для приглашения других пользователей'),
        ),
    ]
