# Generated by Django 3.2.16 on 2023-08-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230817_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='my_invite_code',
            field=models.CharField(default='3CQPhg', editable=False, max_length=6, unique=True, verbose_name='Мой инвайт-код для приглашения других пользователей'),
        ),
    ]
