# Generated by Django 3.2.16 on 2023-08-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230817_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='my_invite_code',
            field=models.CharField(default='CUtNWA', editable=False, max_length=6, unique=True, verbose_name='Мой инвайт-код для приглашения других пользователей'),
        ),
    ]
