# Generated by Django 3.2.16 on 2023-08-17 16:01

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20230817_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='my_invite_code',
            field=models.CharField(default='7CdvsA', editable=False, max_length=6, unique=True, verbose_name='Инвайт-код для приглашения других пользователей'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=12, region=None, unique=True, verbose_name='Номер телефона'),
        ),
    ]
